name: Build and Push Multi-platform Docker Images

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'GitHub 仓库地址 (格式: owner/repo)'
        required: true
      branch:
        description: '分支名称'
        required: true
        default: 'main'
      dockerfile_path:
        description: 'Dockerfile 路径 (相对于仓库根目录)'
        required: true
        default: 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.branch }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract repository name
        id: repo_name
        run: |
          REPO_NAME=$(echo "${{ github.event.inputs.repository }}" | awk -F/ '{print $2}')
          echo "repo_name=${REPO_NAME}" >> $GITHUB_OUTPUT
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ github.event.inputs.dockerfile_path }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo_name.outputs.repo_name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo_name.outputs.repo_name }}:${{ github.event.inputs.branch }}
